version: 2
jobs:
  build:
    docker:
      - image: cimg/elixir:stable
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: NPM Ignore and environment setup
          command: |
            sh .circleci/scripts/replace_sct.sh
            sudo npm i -g npmignore
          
      - run:
          name: Install Newman
          command: 'sudo npm install -g newman'
          
      - run:
          name: API Testing Demo Suite
          command: 'newman run "./Sema4 Test.postman_collection.json"  --environment="./SEMA-Test.postman_environment.json" -d "./badUserpwd.json" -r cli,junit --insecure'
          
      - store_test_results:
          path: ./
